// export { default as useOnClickOutside } from './useOnClickOutside';
export { default as Email } from './Email';
export { default as Footer } from './Footer';
export { default as Head } from './Head';
export { default as Loader } from './Loader';
export { default as Menu } from './Menu';
export { default as Nav } from './Nav';
export { default as Side } from './Side';
export { default as Social } from './Social';
export { default as Layout } from './Layout';
export { default as Name } from './sections/Name';
export { default as About } from './sections/About';
export { default as Jobs } from './sections/Work';
